global using DotNetMvcEight.Core.Entities;
global using DotNetMvcEight.Core.Interfaces.IRepositories.Genric;
global using DotNetMvcEight.Core.ViewModels.Category;
global using DotNetMvcEight.Core.ViewModels.Device;
global using DotNetMvcEight.Core.ViewModels.Game;
global using DotNetMvcEight.Core.CustomValidationAttr;
global using DotNetMvcEight.Web.CustomValidationAttr;
global using Microsoft.AspNetCore.Http;
global using System.ComponentModel.DataAnnotations;